### ISSUE TITLE
VerifyProofs returning incorrect value when run over HTTPS

### ISSUE THREAD

**Issue by gaskills** [chainpoint/chainpoint-client-js#32]
When using the client on a server using HTTPS, the verifyproofs() method returns:

"verified: false" even though it returns the correct "expected value".

When running the same code locally without https it returns verified: "true" for the same proof

For the following proof see example responses:

PROOF:
"eJyNU8tuEzEU/RmWpPG1r1+zisQvsOomsn3vJSOFTJSZFlgWNmy7YIsELWpBbJAQS/4jf4MnCYVGINXjlcfnYfuct7ez0q0Gfjn8XAzDum+m0xempZNu82xaFqldrbt2NUzPzfXwas1fntwtXS9Sv9jOJIFlZZQOSApsjsEHZOWDhkRZoS8xpuwURgbNKlBMxitFgQQNlvR1pJm3NF91xNtHEXUyRasJ+GQnAJwmOZGdKNA+cRTNhX7sIP1Zft4OA++R8zR81wriBPRE2acaGo0NwOkdfek2I721kpj/pk85p0ofsepGHZmP6Ufkv+nN6W3epFVZcH/5+tMyZV5+K2k5H5e6zXz/76pb9+8vPiy3j3c+W2oecsaLj936pl+kibZuB965GMEPOMEx+N2q7Ydz3YD11gYVg6qjySLWkzLWQiTQhLF4oJC1IlTBQbCRomTtJJfsUBdXn6940sWabJP4oBIGT9aJaLSEGQVt8mIKFY4mWHLMSZfko8/kTfYCzoH3zlZtOXY5A8+Q0UQHQoSAkrTFVG1ZnU0QkqqE4CREVhqjYe+VAJW6KRhfwn3CzXbmNEHNZmRRYywLRgmigjbVgxWTATFisAAOqWZUPGQBw2xTVoIFjx1GNADGwuEiQTnTQPO7NvnkT1/G+jQ1Cs0BsbPjOdeJWiyWkiKRcYVzRDZBFSegNIipX+F6D0TCtSKYow4uRxu8vWfnZh+y/vLNrphXVezzIXct3Rxkr882bX+5PfmfxWlF8YrSZnoATMfs/wIo1VZ/"

RESPONSE WITH HTTPS:
[{
anchorId: "4311351"
branch: "cal_anchor_branch"
expectedValue: "50f544512763dfaf2da5361f633cf682c726ccb090348a92c81e124c92db16f1"
hash: "fa15e030284d015b98784e07821adb047c99ab6049e12e08d9a3700d8df434ca"
hashIdCore: "955faee0-17a5-11ea-abba-0194a3c929ee"
hashIdNode: "942a3c20-17a5-11ea-bad5-0127ae9f2ecd"
hashSubmittedCoreAt: "2019-12-05T21:24:13Z"
hashSubmittedNodeAt: "2019-12-05T21:24:11Z"
type: "cal"
uri: "http://167.86.79.59/calendar/4311351/hash"
verified: false
verifiedAt: null
}]

RESPONSE WITHOUT HTTPS:
[{
anchorId: "4311351"
branch: "cal_anchor_branch"
expectedValue: "50f544512763dfaf2da5361f633cf682c726ccb090348a92c81e124c92db16f1"
hash: "fa15e030284d015b98784e07821adb047c99ab6049e12e08d9a3700d8df434ca"
hashIdCore: "955faee0-17a5-11ea-abba-0194a3c929ee"
hashIdNode: "942a3c20-17a5-11ea-bad5-0127ae9f2ecd"
hashSubmittedCoreAt: "2019-12-05T21:24:13Z"
hashSubmittedNodeAt: "2019-12-05T21:24:11Z"
type: "cal"
uri: "http://104.248.8.103/calendar/4311351/hash"
verified: true
verifiedAt: "2019-12-05T21:41:41Z"
}]

**Comment by jacohend** [comment]
Hi @gaskills, thanks for letting us know. If you can give the latest version of master a try, we believe the issue is now fixed there.

**Comment by gaskills** [comment]
@jacohend thanks for responding. This has not fixed the issue.

These are steps i followed to retest:
npm install --save chainpoint/chainpoint-client-js#master
checked index.js in node_modules/chainpoint-client folder includes the new code from fix

then built / deployed app:

The app contains following code:

```
console.log([proof.proof])
let responses = await cp.verifyProofs([proof.proof]);
console.log(responses)
```
In dev environment it logs true and in prod (https) it logs false for both BTC and CP branches.

you can see the logged proof / responses at https://bitcoinwitness.com/ (upload any file and open dev tools console)

any other ideas on what is causing?

Please note: I have left the app interface saying it is verified because I am ignoring the false response being returned from verifyProofs() and have implemented a work around to check expected value using blockcypher but this workaround is clunky and does not allow me to check response expected chainpoint calendar anchor.

**Comment by jacohend** [comment]
@gaskills We believe the issue could have been an un-updated webpack bundle. We've updated this and pushed to npm as version 0.4.2. Can you try this and let us know?

**Comment by gaskills** [comment]
@jacohend you are awesome! thankyou it is working now!

**Comment by jacohend** [comment]
Great to hear! All credit goes to our co-founder, @jasonbukowski, for the fix.
